-- Update cities to display states instead of city names

UPDATE city SET name = 'Alabama', subdomain = 'alabama' WHERE id = 211;
UPDATE city SET name = 'Alaska', subdomain = 'alaska' WHERE id = 212;
UPDATE city SET name = 'Arizona', subdomain = 'arizona' WHERE id = 213;
UPDATE city SET name = 'Arkansas', subdomain = 'arkansas' WHERE id = 214;
UPDATE city SET name = 'California', subdomain = 'california' WHERE id = 215;
UPDATE city SET name = 'Colorado', subdomain = 'colorado' WHERE id = 216;
UPDATE city SET name = 'Connecticut', subdomain = 'connecticut' WHERE id = 217;
UPDATE city SET name = 'Delaware', subdomain = 'delaware' WHERE id = 218;
UPDATE city SET name = 'Florida', subdomain = 'florida' WHERE id = 219;
UPDATE city SET name = 'Georgia', subdomain = 'georgia' WHERE id = 220;
UPDATE city SET name = 'Hawaii', subdomain = 'hawaii' WHERE id = 221;
UPDATE city SET name = 'Idaho', subdomain = 'idaho' WHERE id = 222;
UPDATE city SET name = 'Illinois', subdomain = 'illinois' WHERE id = 223;
UPDATE city SET name = 'Indiana', subdomain = 'indiana' WHERE id = 224;
UPDATE city SET name = 'Iowa', subdomain = 'iowa' WHERE id = 225;
UPDATE city SET name = 'Kansas', subdomain = 'kansas' WHERE id = 226;
UPDATE city SET name = 'Kentucky', subdomain = 'kentucky' WHERE id = 227;
UPDATE city SET name = 'Louisiana', subdomain = 'louisiana' WHERE id = 228;
UPDATE city SET name = 'Maine', subdomain = 'maine' WHERE id = 229;
UPDATE city SET name = 'Maryland', subdomain = 'maryland' WHERE id = 230;
UPDATE city SET name = 'Massachusetts', subdomain = 'massachusetts' WHERE id = 231;
UPDATE city SET name = 'Michigan', subdomain = 'michigan' WHERE id = 232;
UPDATE city SET name = 'Minnesota', subdomain = 'minnesota' WHERE id = 233;
UPDATE city SET name = 'Mississippi', subdomain = 'mississippi' WHERE id = 234;
UPDATE city SET name = 'Missouri', subdomain = 'missouri' WHERE id = 235;
UPDATE city SET name = 'Montana', subdomain = 'montana' WHERE id = 236;
UPDATE city SET name = 'Nebraska', subdomain = 'nebraska' WHERE id = 237;
UPDATE city SET name = 'Nevada', subdomain = 'nevada' WHERE id = 238;
UPDATE city SET name = 'New Hampshire', subdomain = 'newhampshire' WHERE id = 239;
UPDATE city SET name = 'New Jersey', subdomain = 'newjersey' WHERE id = 240;
UPDATE city SET name = 'New Mexico', subdomain = 'newmexico' WHERE id = 241;
UPDATE city SET name = 'New York', subdomain = 'newyork' WHERE id = 242;
UPDATE city SET name = 'North Carolina', subdomain = 'northcarolina' WHERE id = 243;
UPDATE city SET name = 'North Dakota', subdomain = 'northdakota' WHERE id = 244;
UPDATE city SET name = 'Ohio', subdomain = 'ohio' WHERE id = 245;
UPDATE city SET name = 'Oklahoma', subdomain = 'oklahoma' WHERE id = 246;
UPDATE city SET name = 'Oregon', subdomain = 'oregon' WHERE id = 247;
UPDATE city SET name = 'Pennsylvania', subdomain = 'pennsylvania' WHERE id = 248;
UPDATE city SET name = 'Rhode Island', subdomain = 'rhodeisland' WHERE id = 249;
UPDATE city SET name = 'South Carolina', subdomain = 'southcarolina' WHERE id = 250;
UPDATE city SET name = 'South Dakota', subdomain = 'southdakota' WHERE id = 251;
UPDATE city SET name = 'Tennessee', subdomain = 'tennessee' WHERE id = 252;
UPDATE city SET name = 'Texas', subdomain = 'texas' WHERE id = 253;
UPDATE city SET name = 'Utah', subdomain = 'utah' WHERE id = 254;
UPDATE city SET name = 'Vermont', subdomain = 'vermont' WHERE id = 255;
UPDATE city SET name = 'Virginia', subdomain = 'virginia' WHERE id = 256;
UPDATE city SET name = 'Washington', subdomain = 'washington' WHERE id = 257;
UPDATE city SET name = 'West Virginia', subdomain = 'westvirginia' WHERE id = 258;
UPDATE city SET name = 'Wisconsin', subdomain = 'wisconsin' WHERE id = 259;
UPDATE city SET name = 'Wyoming', subdomain = 'wyoming' WHERE id = 260;
UPDATE city SET name = 'District of Columbia', subdomain = 'washingtondc' WHERE id = 261;
