-- Базовая схема: снята с работающей базы production 2026-08-20.
--
-- До этого схему держал Hibernate через ddl-auto=update, а инструмента миграций
-- не было. Файл описывает состояние на момент подключения Flyway; дальше все
-- изменения схемы идут отдельными версиями V2, V3 и так далее.
--
-- Существующая база принимает этот файл как уже применённый (flyway.baseline-on-
-- migrate), поэтому повторно он там не выполняется. На чистой базе создаёт всё
-- с нуля.

CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color varchar(255),
    description varchar(500),
    icon varchar(255),
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cities (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255) NOT NULL,
    subdomain varchar(64)
);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamptz,
    expires_at timestamptz NOT NULL,
    purpose varchar(32) NOT NULL,
    token varchar(128) NOT NULL,
    used_at timestamptz,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamptz,
    listing_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS keyword_filters (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active boolean NOT NULL,
    category varchar(255) NOT NULL,
    created_at timestamptz NOT NULL,
    severity integer NOT NULL,
    word varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS listing_flags (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamptz NOT NULL,
    description text,
    reason varchar(255) NOT NULL,
    resolved_at timestamptz,
    resolved_by varchar(255),
    status varchar(255) NOT NULL,
    listing_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS listing_images (
    listing_id bigint NOT NULL,
    image_url varchar(255)
);

CREATE TABLE IF NOT EXISTS listing_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    admin_notes text,
    created_at timestamptz,
    details text,
    reason varchar(32) NOT NULL,
    reporter_ip varchar(64),
    reviewed_at timestamptz,
    status varchar(32) NOT NULL,
    listing_id bigint NOT NULL,
    reporter_id bigint,
    reviewed_by_id bigint
);

CREATE TABLE IF NOT EXISTS listings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    area varchar(255),
    auto_hidden boolean NOT NULL DEFAULT false,
    created_at timestamptz,
    deleted_at timestamptz,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    is_featured boolean NOT NULL DEFAULT false,
    is_test boolean NOT NULL DEFAULT false,
    location varchar(255) NOT NULL,
    price double precision NOT NULL,
    promoted_until timestamptz,
    status varchar(255) NOT NULL,
    title varchar(200) NOT NULL,
    views integer,
    category_id bigint,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content text NOT NULL,
    created_at timestamptz,
    is_read boolean,
    is_support_message boolean,
    listing_id bigint,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS social_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamptz,
    email varchar(255),
    name varchar(255),
    picture varchar(255),
    provider varchar(255) NOT NULL,
    provider_id varchar(255) NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS subcategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color varchar(255),
    description varchar(500),
    icon varchar(255),
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    category_id bigint NOT NULL,
    parent_id bigint,
    sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS us_city (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(128) NOT NULL,
    population integer NOT NULL,
    state_code varchar(2) NOT NULL,
    state_name varchar(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category varchar(255) NOT NULL,
    comment text,
    created_at timestamptz NOT NULL,
    rating integer NOT NULL,
    listing_id bigint,
    rated_user_id bigint NOT NULL,
    rater_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city varchar(255),
    created_at timestamptz,
    email varchar(255) NOT NULL,
    email_verified boolean,
    email_verified_at timestamptz,
    is_admin boolean,
    password varchar(255) NOT NULL,
    phone varchar(255),
    username varchar(255) NOT NULL
);

-- Первичные ключи
ALTER TABLE categories ADD PRIMARY KEY (id);
ALTER TABLE cities ADD PRIMARY KEY (id);
ALTER TABLE email_verification_tokens ADD PRIMARY KEY (id);
ALTER TABLE favorites ADD PRIMARY KEY (id);
ALTER TABLE keyword_filters ADD PRIMARY KEY (id);
ALTER TABLE listing_flags ADD PRIMARY KEY (id);
ALTER TABLE listing_reports ADD PRIMARY KEY (id);
ALTER TABLE listings ADD PRIMARY KEY (id);
ALTER TABLE messages ADD PRIMARY KEY (id);
ALTER TABLE social_accounts ADD PRIMARY KEY (id);
ALTER TABLE subcategories ADD PRIMARY KEY (id);
ALTER TABLE us_city ADD PRIMARY KEY (id);
ALTER TABLE user_ratings ADD PRIMARY KEY (id);
ALTER TABLE users ADD PRIMARY KEY (id);

-- Ограничения: внешние ключи, уникальность, проверки
ALTER TABLE categories ADD CONSTRAINT ukoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug);
ALTER TABLE cities ADD CONSTRAINT ukl61tawv0e2a93es77jkyvi7qa UNIQUE (name);
ALTER TABLE cities ADD CONSTRAINT uktkqr49nfkxqe6kg5yka9mv63u UNIQUE (subdomain);
ALTER TABLE email_verification_tokens ADD CONSTRAINT email_verification_tokens_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['EMAIL_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])));
ALTER TABLE email_verification_tokens ADD CONSTRAINT fki1c4mmamlb8keqt74k4lrtwhc FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE email_verification_tokens ADD CONSTRAINT idx_evt_token UNIQUE (token);
ALTER TABLE favorites ADD CONSTRAINT fkk7du8b8ewipawnnpg76d55fus FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE favorites ADD CONSTRAINT fkoc425aeu56owvlscxwvuwsu4n FOREIGN KEY (listing_id) REFERENCES listings(id);
ALTER TABLE favorites ADD CONSTRAINT uki9yqqgg83yv72ftta12j4nfws UNIQUE (user_id, listing_id);
ALTER TABLE keyword_filters ADD CONSTRAINT keyword_filters_category_check CHECK (((category)::text = ANY ((ARRAY['SPAM'::character varying, 'PROHIBITED_ITEM'::character varying, 'ABUSE'::character varying])::text[])));
ALTER TABLE keyword_filters ADD CONSTRAINT ukrnkdl6slykxlj2w7l46is44cn UNIQUE (word);
ALTER TABLE listing_flags ADD CONSTRAINT fk7mtod70tppjgoiolmcri18yee FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE listing_flags ADD CONSTRAINT fks6aqv3a5cuv57vjqdg0ri37vd FOREIGN KEY (listing_id) REFERENCES listings(id);
ALTER TABLE listing_flags ADD CONSTRAINT listing_flags_reason_check CHECK (((reason)::text = ANY ((ARRAY['SPAM'::character varying, 'PROHIBITED_ITEM'::character varying, 'FRAUD_SCAM'::character varying, 'OFFENSIVE_CONTENT'::character varying, 'INVALID_CONTACT'::character varying, 'DUPLICATE'::character varying, 'OTHER'::character varying])::text[])));
ALTER TABLE listing_flags ADD CONSTRAINT listing_flags_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'REVIEWED'::character varying, 'RESOLVED'::character varying, 'DISMISSED'::character varying])::text[])));
ALTER TABLE listing_images ADD CONSTRAINT fkq8bkplrutxrfur5u7pppml04y FOREIGN KEY (listing_id) REFERENCES listings(id);
ALTER TABLE listing_reports ADD CONSTRAINT fk3vfn5w5g0yllxftti3ldjy45h FOREIGN KEY (reporter_id) REFERENCES users(id);
ALTER TABLE listing_reports ADD CONSTRAINT fkf0qbj5353m4ni1b0f96v0cvs6 FOREIGN KEY (reviewed_by_id) REFERENCES users(id);
ALTER TABLE listing_reports ADD CONSTRAINT fkolefxkr4r0trywnergu0l4sxa FOREIGN KEY (listing_id) REFERENCES listings(id);
ALTER TABLE listing_reports ADD CONSTRAINT listing_reports_reason_check CHECK (((reason)::text = ANY ((ARRAY['FRAUD'::character varying, 'SPAM'::character varying, 'INAPPROPRIATE'::character varying, 'PROHIBITED_ITEM'::character varying, 'DUPLICATE'::character varying, 'MISLEADING'::character varying, 'COPYRIGHT'::character varying, 'OTHER'::character varying])::text[])));
ALTER TABLE listing_reports ADD CONSTRAINT listing_reports_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'REVIEWED_VALID'::character varying, 'REVIEWED_INVALID'::character varying, 'DISMISSED'::character varying])::text[])));
ALTER TABLE listings ADD CONSTRAINT fkb5kgkbggc40jyxeq28onih2x1 FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE listings ADD CONSTRAINT fkbyfn7t3i7g0f11pcy5veh088p FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE listings ADD CONSTRAINT listings_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'HIDDEN'::character varying, 'FLAGGED'::character varying, 'BANNED'::character varying, 'EXPIRED'::character varying, 'DELETED'::character varying])::text[])));
ALTER TABLE messages ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES users(id);
ALTER TABLE messages ADD CONSTRAINT fkq4pvtu9s5dw5igbibathqr8ea FOREIGN KEY (listing_id) REFERENCES listings(id);
ALTER TABLE messages ADD CONSTRAINT fkt05r0b6n0iis8u7dfna4xdh73 FOREIGN KEY (receiver_id) REFERENCES users(id);
ALTER TABLE social_accounts ADD CONSTRAINT fk6rmxxiton5yuvu7ph2hcq2xn7 FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE social_accounts ADD CONSTRAINT ukq7w5kmcebma8jj941snwctfju UNIQUE (provider, provider_id);
ALTER TABLE subcategories ADD CONSTRAINT fkiborb6ptvy1t1n3v6klb56l5s FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE subcategories ADD CONSTRAINT fkpyx4y2g2wie1xv7gk0pni0eic FOREIGN KEY (parent_id) REFERENCES subcategories(id);
ALTER TABLE subcategories ADD CONSTRAINT uk6di7pqd69hlsa6539vbdxrb1v UNIQUE (category_id, slug);
ALTER TABLE user_ratings ADD CONSTRAINT fk15v350ga8791sfkfa0pntha2 FOREIGN KEY (listing_id) REFERENCES listings(id);
ALTER TABLE user_ratings ADD CONSTRAINT fk41kdmatdgldc18ekgnwpkcsh3 FOREIGN KEY (rater_id) REFERENCES users(id);
ALTER TABLE user_ratings ADD CONSTRAINT fkcbrdshhb7e80hhs4pf5xkxlxi FOREIGN KEY (rated_user_id) REFERENCES users(id);
ALTER TABLE user_ratings ADD CONSTRAINT user_ratings_category_check CHECK (((category)::text = ANY ((ARRAY['COMMUNICATION'::character varying, 'ITEM_QUALITY'::character varying, 'SELLER_TRUST'::character varying, 'BUYER_TRUST'::character varying])::text[])));
ALTER TABLE users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

-- Индексы (первичные ключи и уникальность создали свои выше)
CREATE INDEX idx_evt_user_id ON public.email_verification_tokens USING btree (user_id);
CREATE INDEX idx_active ON public.keyword_filters USING btree (active);
CREATE INDEX idx_word ON public.keyword_filters USING btree (word);
CREATE INDEX idx_report_listing ON public.listing_reports USING btree (listing_id);
CREATE INDEX idx_report_status ON public.listing_reports USING btree (status);
CREATE INDEX ix_us_city_state_lower_name ON public.us_city USING btree (state_code, lower((name)::text));
CREATE INDEX ix_us_city_state_population ON public.us_city USING btree (state_code, population DESC);
CREATE UNIQUE INDEX ux_us_city_name_state ON public.us_city USING btree (name, state_code);
